name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '21.6.2'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        
      - name: Deploy to production url
        # main is the branch name where new code is pushed
        if: github.ref == 'refs/heads/main'

        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.


# go the repo settings, Action > General > Workflow permissions
# and select Read and Write permissions
# click save,